### ISSUE TITLE
Could not start postgres after docker-compose up

### ISSUE THREAD

**Issue by janbro1** [brocaar/chirpstack-docker#18]
Used current docker-compose-env.yaml
After pull and during build with docker-compose up I get: 
ERROR: for postgresql  Cannot start service postgresql: Bind mount failed: '/volume1/docker/yml/lorawan/configuration/postgresql/initdb' does not exists
ERROR: Encountered errors while bringing up the project.

**Comment by haimiko** [comment]
I had to manually run postgres first, exec into the container and run the init commands manually.

**Comment by janbro1** [comment]
that worked once for me. After an update I am no longer able to bash into the lora app container. When I bash into the postgresql and execute the scripts I get an (after I switch to the postgres user) loraserver_ns already exists.
What options do I have?

**Comment by brocaar** [comment]
This look like a file sharing issue to me between the Windows host and Linux guest system (running the Docker containers). I'm not sure what the solution is, but I would look into that direction when debugging this issue.

**Comment by haimiko** [comment]
> This look like a file sharing issue to me between the Windows host and Linux guest system (running the Docker containers). I'm not sure what the solution is, but I would look into that direction when debugging this issue.

FYI.  Not related to my issue. I'm running on Ubuntu 16.04

**Comment by janbro1** [comment]
same here I am also running on Linux, not Windows.

**Comment by geeks-r-us** [comment]
For me issue of not starting postgresql was fixed by adding environment variable POSTGRES_PASSWORD to postgresql like this:

`
environment:      
      - POSTGRES_PASSWORD=password
`

**Comment by brocaar** [comment]
This should be fixed in the last version of the repo which includes the above fix.
