### ISSUE TITLE
`docker-compose up` fails with docker-ce

### ISSUE THREAD

**Issue by jcwren** [brocaar/chirpstack-docker#23]
Installed docker per the Debian instructions, the following two components were installed:
```
$ sudo apt-get install docker-ce docker-ce-cli containerd.io
<usual apt-get noise>
Setting up docker-ce-cli (5:19.03.3~3-0~debian-stretch) ...
Setting up docker-ce (5:19.03.3~3-0~debian-stretch) ...
...
$ docker-compose --version
docker-compose version 1.9.0, build 2585387
$ docker --version
Docker version 19.03.3, build a872fc2f86
$
```

Ran `docker-compose up` command, received the following error:

```
$ docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
$
```

I'm pretty new to Docker, so I don't know what I should be looking at to resolve this.

**Comment by blocknonip** [comment]
According to the docker-compose release history [here](https://docs.docker.com/release-notes/docker-compose/), you're using a version from 2016. You will need a newer version that supports format version 3.

**Comment by jcwren** [comment]
Well, that's interesting. I directly followed the installation instructions from https://docs.docker.com/install/linux/docker-ce/debian/.

**Comment by brocaar** [comment]
You forgot to setup the Docker respository (https://docs.docker.com/install/linux/docker-ce/debian/#install-using-the-repository). Because of that you pulled Docker from the Debian repository (which usually lags a bit behind).
