### ISSUE TITLE
Repository name inconsistent with quickstart page

### ISSUE THREAD

**Issue by kuanyili** [brocaar/chirpstack-docker#24]
In [Quickstart using Docker Compose](https://www.chirpstack.io/guides/docker-compose/), it points readers to [chirpstack-docker](https://github.com/brocaar/chirpstack-docker) and it is now still [loraserver-docker](https://github.com/brocaar/loraserver-docker). The repository name needs to be changed accordingly.

**Comment by brocaar** [comment]
:+1: fixed.
