### ISSUE TITLE
添加 Network-servers 报错

### ISSUE THREAD

**Issue by chenzhixion** [brocaar/chirpstack-docker#25]
![image](https://user-images.githubusercontent.com/32694761/68171798-29ac5e80-ffb0-11e9-8af0-5d9277baaf93.png)

**Comment by blocknonip** [comment]
See https://github.com/brocaar/chirpstack-docker#add-network-server .

**Comment by jcwren** [comment]
The documentation is not entirely correct. In the last paragraph, where it says

> When using the above example, it means you must enter `networkserver:8000` as the network-server hostname:IP."

 it should really say `chirpstack-network-server:8000`, as most people getting started are going to be using the defaults. Or add an additional sentence that says something to effect of "When using the default docker-compose values, the address would be `chirpstack-network-server:8000`"

**Comment by brocaar** [comment]
@jcwren would you mind creating a pull-request with the proposed changes?

**Comment by jcwren** [comment]
@brocaar, I was taking a shot at this, but ran into an issue I mentioned in the community forum at https://forum.chirpstack.io/t/how-to-build-the-docker-image/3368/9?u=jcwren

**Comment by blocknonip** [comment]
I'm a little confused by this thread. The documentation (the README for this project) does say `chirpstack-network-server:8000`, and it did as of 17 days ago:

https://github.com/brocaar/chirpstack-docker/commit/b753aaf6f7bad968d5e1af91e61206f2b6272ccc#diff-04c6e90faac2675aa89e2176d2eec7d8R58

**Comment by jcwren** [comment]
This page does not: https://www.chirpstack.io/guides/docker-compose/

**Comment by blocknonip** [comment]
Ah, very good. Thanks.
