### ISSUE TITLE
docker-compose up created Postgres Account I can connect to without password

### ISSUE THREAD

**Issue by NoelzeN** [brocaar/chirpstack-docker#27]
When trying to debug a different issue I came across something which looks like an issue to me (Correct me if I'm wrong and just have some big misunderstanding how authentication with psql works):

1) Create a Loraserver Setup with docker-compose up. 
Things I changed in the docker file:
- Remove the Mosquitto Container as I don't need that
- Give each container a fixed IP Address
Things I changed in the Config Folder:
- postgresql: Nothing
- network-server: MQTT Connction Parameters

2) Expected Behavior: The docker-compose up command should create a psql database and user with the default credentials from the 001-init-chirpstack_ns.sh file:
```
    create role chirpstack_ns with login password 'chirpstack_ns';
    create database chirpstack_ns with owner chirpstack_ns;
```

3) Testing: I tried to connect to the Database from command line:
`psql -h 172.23.0.24 -p 5432 -U chirpstack_ns -W`

4) Actual Behavior: It asks me for a password, but even when I give the password "asdf" or anything else it connects successfully. Even when connected to psql I can connect to the database by giving a wrong password:

```
[...]$ psql -h 172.23.0.24 -p 5432 -U chirpstack_ns -W 
Password for user chirpstack_ns: 
psql (9.2.24, server 9.6.16)
WARNING: psql version 9.2, server version 9.6.
         Some psql features might not work.
Type "help" for help.

chirpstack_ns=> \connect chirpstack_ns
Password for user chirpstack_ns: 
psql (9.2.24, server 9.6.16)
WARNING: psql version 9.2, server version 9.6.
         Some psql features might not work.
You are now connected to database "chirpstack_ns" as user "chirpstack_ns".
```

Somewhere in the back of my head I remember that Postgres authenticates by the unix user you use to login but I'm not 100% sure how it actually works to be honest. So is this one a bug or am I misunderstanding authentication in psql completely? It doesn't matter whether I try to authenticate directly from the host system or from within the Network Server Docker container, both work fine. Also if I change the Password in the network-server configuration file and do a docker-compose down and then a docker-compose up the Network Server can still connect to the Database.

**Comment by brocaar** [comment]
This `docker-compose.yml` file is intended to demonstrate a working setup, it is not intended to be production ready. See in the README:

> Note: Please use this docker-compose.yml file as a starting point for testing but keep in mind that for production usage it might need modifications.

It might be that there are some PostgreSQL flags that you can tweak in the postgresql image for authentication / authorization, but https://hub.docker.com/_/postgres would be a better source for this :-)
