### ISSUE TITLE
gRPC DNS resolution doesn't seem to work

### ISSUE THREAD

**Issue by evil-dog** [brocaar/chirpstack-docker#35]
It seems that in the current version that gRPC DNS resolution is broken. As far as I can tell this is an issue with gRPC and not chirpstack as everything works fine if you use IP addresses.

I've filed an issue against gRPC for this.
https://github.com/grpc/grpc-go/issues/3572

Wanted to file this here for FYI for others and to track updating gRPC once the issue is resolved over there.

**Comment by blocknonip** [comment]
I am seeing this a lot in production now. It usually happens when there is a node count change in Kubernetes and pods get shuffled around. Frequently, the ChirpStack containers (NS or AS) never update to the new DNS for their self-ingress/services (those that they use to connect to each other via gRPC), no matter how long they are running.

The immediate fix is to kill them, and let them restart with new DNS successfully being picked up. As a workaround, we've raised their priority to minimize pod shuffling, but even that isn't a complete fix.

I don't recall when this started, but I noticed it a lot more in the past couple releases. Historically, ChirpStack pods were our most reliable when it came to reconnection logic, and now it seems we need to manually intervene any time there is a topology change.

 @brocaar Any thoughts on gRPC and DNS? Or if this gRPC at all?

**Comment by evil-dog** [comment]
Sorry not too familiar with Kubernetes, so not sure how to relate this to a Docker-compose setup.

From what I'm experiencing DNS seems to be working and updating just fine. Chirpstack AS and NS both connect to and communicate with redis, postgresql and mosquitto just fine. It's only the gRPC comms between NS and AS that fail. When I assign static IPs to the containers and use the IPs for NA and AS everything works perfectly. And I know the docker DNS proxy is updating correctly as I've been able to check using nslookup within the AS and NS containers.

As for killing and restarting, I'm not sure if you're talking about restarting the container or going and killing the process in the container. But no matter how I have tried to restart the container (restart or down/up) the same issues happens. I did not try killing the AS or NS process itself within the container though. However, since redis, postgresql, and mosquitto all seem to work perfectly fine throughout and gRPC is the only thing with an issue, I think this suggests that gRPC has an underlying issue with it's DNS resolution code.

**Comment by Kampe** [comment]
We're seeing the same issues when running in docker-compose

**Comment by brocaar** [comment]
It could be that this is related to this change: https://github.com/brocaar/chirpstack-network-server/commit/1d20dbb85f07c79ccffcd2899347605e6fa31eee ?

This was introduced to support DNS based load-balancing. 

```
	dialOptions := []grpc.DialOption{
		grpc.WithBalancerName(roundrobin.Name),
	}
```

Is there to enable roundrobin load-balancing. 

```
	// the default is passthrough, see:
	// https://github.com/grpc/grpc-go/issues/1783
	resolver.SetDefaultScheme("dns")
```

Is there to make sure the documented default scheme is used. The default in Go is `passthrough`, but the documented default is `dns`:

> The URI scheme indicates what resolver plugin to use. If no scheme prefix is specified or the scheme is unknown, the **dns** scheme is used by default.

https://github.com/grpc/grpc/blob/master/doc/naming.md#name-syntax

There was a TXT related issue to this change, but this has been fixed in the latest gRPC version and has been updated in the ChirpStack NS and AS.: https://github.com/brocaar/chirpstack-application-server/issues/426.

---

**General questions to all of you:**

### Please report the exact error you are seeing

I assume this is?

```
chirpstack-network-server_1 | time="2020-04-27T05:06:18Z" level=warning msg="creating insecure application-server client" server="chirpstack-application-server:8001"
chirpstack-network-server_1 | time="2020-04-27T05:06:23Z" level=warning msg="ccResolverWrapper: reporting error to cc: dns: A record lookup error: lookup chirpstack-application-server on 127.0.0.11:53: dial udp 127.0.0.11:53: operation was canceled"
chirpstack-network-server_1 | time="2020-04-27T05:06:23Z" level=error msg="gateway: handle gateway stats error" ctx_id=68623603-d2d2-4f2c-a6e4-34f56eae1dad error="get application-server client error: get application-server client error: create application-server api client error: dial application-server api error: context deadline exceeded"
```

That way I don't have to make any assumptions what "same issue" means :-)

### Please report the exact versions that you are using

When the ChirpStack components start, they will print the version to the logs. Using the latest chirpstack-docker doesn't mean you are using the latest ChirpStack components as Docker images and containers are cached.

Knowing the exact versions is quite helpful ;-)

**Comment by evil-dog** [comment]
Running chirpstack versions.

```
chirpstack-application-server_1  | time="2020-04-27T06:12:55Z" level=info msg="starting ChirpStack Application Server" docs="https://www.chirpstack.io/" version=3.10.0

chirpstack-network-server_1      | time="2020-04-27T06:12:50Z" level=info msg="starting ChirpStack Network Server" band=US915 docs="https://www.chirpstack.io/" net_id=ca571e version=3.9.0
```

hmm, could be related to the roundrobin, but still sounds like a bug in gRPC as it should still work if there is only a single address provided from DNS.

**Comment by evil-dog** [comment]
I just did a test with the application server and removed the load balancer line and I got the same error as before, so not sure it's related to the load balancer.

Line removed:
internal/backend/networkserver/networkserver.go:
```112:             grpc.WithBalancerName(roundrobin.Name),```

**Comment by evil-dog** [comment]
For anyone not following along on the grpc-go issue. I've pulled together some sample code that reproduces most of the original issue. You can find the code here:

https://github.com/evil-dog/grpc-go-issue-3572-repro

**Comment by rtriveurbana** [comment]
I've the same problem on the docker-compose unfortunately

**Comment by peter3099** [comment]
Hi 

Any way around  this? 
This is my config 
`version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:latest
    # environment:
    #   - POSTGRESQL__DSN=postgres://chirpstack_ns:chirpstack_ns@postgresql/chirpstack_ns?sslmode=disable
    #   - REDIS__URL=redis://redis:6379
    #   - NETWORK_SERVER__BAND__NAME=EU868
    #   - NETWORK_SERVER__GATEWAY__BACKEND__MQTT__SERVER=tcp://mosquitto:1883
    #   - JOIN_SERVER__DEFAULT__SERVER=http://172.28.1.3:8003
    #   - GEOLOCATION_SERVER__SERVER=172.28.1.5:8005
    # ports:
    #   - 8000:8000
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server
    networks:
      default:
        ipv4_address: 172.28.1.2

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:latest
    # environment:
    #   - POSTGRESQL__DSN=postgres://chirpstack_as:chirpstack_as@postgresql/chirpstack_as?sslmode=disable
    #   - REDIS__URL=redis://redis:6379
    #   - APPLICATION_SERVER__INTEGRATION__MQTT__SERVER=tcp://mosquitto:1883
    #   - APPLICATION_SERVER__API__PUBLIC_HOST=172.28.1.3:8001
    #   - APPLICATION_SERVER__EXTERNAL_API__JWT_SECRET=verysecret
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server
    ports:
      - 8080:8080
    networks:
      default:
        ipv4_address: 172.28.1.3

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:latest
    ports:
      - 1700:1700/udp
    # environment:
    #   - INTEGRATION__MQTT__AUTH__GENERIC__SERVERS=tcp://mosquitto:1883
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    networks:
      default:
        ipv4_address: 172.28.1.4

  chirpstack-geolocation-server:
    image: chirpstack/chirpstack-geolocation-server:latest
    # environment:
    #   - GEO_SERVER__BACKEND__NAME=collos
    volumes:
      - ./configuration/chirpstack-geolocation-server:/etc/chirpstack-geolocation-server
    networks:
      default:
        ipv4_address: 172.28.1.5

  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 172.28.1.6

  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    networks:
      default:
        ipv4_address: 172.28.1.7

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    networks:
      default:
        ipv4_address: 172.28.1.8

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
`
I tried using the fixed IP, then I get the network server added on to the application server, but when it wants to register the gateway 

`time="2020-08-25T09:01:17Z" level=info msg="gateway/mqtt: gateway stats packet received" gateway_id=XXXXXXXXXXXX stats_id=2fc6221f-f9ea-421b-aaf8-42fb10ea4bfc


time="2020-08-25T09:01:17Z" level=info msg="gateway updated" ctx_id=2fc6221f-f9ea-421b-aaf8-42fb10ea4bfc gateway_id=XXXXXXXXXXXX


time="2020-08-25T09:01:17Z" level=warning msg="creating insecure application-server client" server="chirpstack-application-server:8001"


time="2020-08-25T09:01:22Z" level=warning msg="ccResolverWrapper: reporting error to cc: dns: A record lookup error: lookup chirpstack-application-server on 127.0.0.11:53: dial udp 127.0.0.11:53: operation was canceled"


time="2020-08-25T09:01:22Z" level=error msg="gateway: handle gateway stats error" ctx_id=2fc6221f-f9ea-421b-aaf8-42fb10ea4bfc error="get application-server client error: get application-server client error: create application-server api client error: dial application-server api error: context deadline exceeded"`


I don't understand why it keep looking for chirpstack-application-server:8001 I already change it in the conf files and also on the env variables but I cannot find a way to set up the fix IP for this.

Any help would be appreciated, I added it here as I thought is related to the issue but let me know if I have to open a new one
Thanks

**Comment by Swap-File** [comment]
Same problem here, any suggestions on getting the docker compose to work?

chirpstack-application-server_1  | time="2020-09-21T17:41:45Z" level=warning msg="creating insecure network-server client" server="chirpstack-network-server:8000 "
chirpstack-application-server_1  | time="2020-09-21T17:41:50Z" level=warning msg="ccResolverWrapper: reporting error to cc: dns: A record lookup error: lookup chirpstack-network-server on 127.0.0.11:53: dial udp 127.0.0.11:53: operation was canceled"
chirpstack-application-server_1  | time="2020-09-21T17:41:50Z" level=error msg="finished unary call with code Unknown" ctx_id=f5a614f6-5402-4f2a-bcb3-5efcdfd9379f error="rpc error: code = Unknown desc = context deadline exceeded" grpc.code=Unknown grpc.method=Create grpc.service=api.NetworkServerService grpc.start_time="2020-09-21T17:41:45Z" grpc.time_ms=5028.882 peer.address="127.0.0.1:58598" span.kind=server system=grpc

**Comment by Swap-File** [comment]
My quick fix solution was to set up an ubuntu vm and follow the directions here, it went faster and smoother than the docker compose:
https://www.chirpstack.io/project/guides/debian-ubuntu/

**Comment by brocaar** [comment]
I have been looking at this again, and potentially this issue might have been introduced after this line which has been added to all components:

```
resolver.SetDefaultScheme("dns")
```

I'm going to change this into a configuration option which can be enabled to see if this solves the issue.

**Comment by zielen** [comment]
If your host has static IP you can work around this bug by using it instead of application server hostname. Besides changing the value in config file I needed to change it in postgres database chirpstack_ns, table routing_profile. Then just add port 8001 and 8803 to docker-compose.yml
`  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:latest
    ports:
      - 8080:8080
      - 8001:8001
      - 8003:8003
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server`
If for any reason you dont want to expose these ports to the public, you can make virtual network adapter with private ip and then use its ip in config files and when exposing ports: https://docs.docker.com/compose/compose-file/#ports

**Comment by brocaar** [comment]
Do you still experience this issue with the latest ChirpStack components? The change I proposed on Oct. 16 is already part of the latest versions. Else I will close this issue.

**Comment by peter3099** [comment]
Hi brocar all working ok now, I'll close the issue. THanks

**Comment by evil-dog** [comment]
I've finally gotten back to playing with Lora and Chirpstack. This issue seems to not be occuring in the current Chirpstack version.

**Comment by brocaar** [comment]
Thanks for confirming @evil-dog. I'll close this issue.

**Comment by Shrulabh25** [comment]
@brocaar 
I'm still facing this issue

```
<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "DNS resolution failed for https://nnxx.com/: C-ares status is not ARES_SUCCESS qtype=AAAA name=https is_balancer=0: Domain name not found"
        debug_error_string = "UNKNOWN:DNS resolution failed for https://nnxx.com/: C-ares status is not ARES_SUCCESS qtype=AAAA name=https is_balancer=0: Domain name not found {created_time:"2024-03-11T09:45:20.354939546+00:00", grpc_status:14}"
>
ERROR:root:GRPC Exception:  DNS resolution failed for https://nnxx.com/: C-ares status is not ARES_SUCCESS qtype=AAAA name=https is_balancer=0: Domain name not found
```

My code 
```
BASE_URL = "https://nnxx.com"  # opens chirpstack v4 UI
channel = grpc.insecure_channel(BASE_URL)
device_stub = api.device_pb2_grpc.DeviceServiceStub(channel)

```
