### ISSUE TITLE
Problems connecting chirpstack-gateway-bridge with DRAGINO LG308 Gateway

### ISSUE THREAD

**Issue by Rokscript08** [brocaar/chirpstack-docker#36]
Hi,  
I have recently changed to ChirpStack Private Server and installed this docker version. Seems to work pretty good. But my gateway isn't connecting, or at least in the Application Server it still says  
_Last seen: Never_  
When looking for the logs, _docker-compose logs_ will show:  
_chirpstack-gateway-bridge_1      | time="2020-06-11T07:55:32Z" level=error msg="integration/mqtt: connection error" error="Network Error : dial tcp 172.20.0.4:1883: connect: connection refused"_

> I followed this guide to install in the gateway: https://www.chirpstack.io/gateway-bridge/gateway/dragino/ to install

> This is the configuration file on docker:  
[chirpstack-gateway-bridge.toml.txt](https://github.com/brocaar/chirpstack-docker/files/4763445/chirpstack-gateway-bridge.toml.txt)
(I recently changed 127.0.0.1 to chirpstack-network-server as shown in the file)

> And this the file on the gateway:  
[GTWFILE_chirpstack-gateway-bridge.toml.txt](https://github.com/brocaar/chirpstack-docker/files/4763478/GTWFILE_chirpstack-gateway-bridge.toml.txt)

(Maybe I'm missing sth?)  
Any help is really useful.  
Nicolas

**Comment by sophiekovalevsky** [comment]
@Rokscript08 as the issue does not look like a problem to report, I suggest to write this issue down into the [Community Forum. ](https://forum.chirpstack.io/) In there, you will find a lot people that may help you on this. 

From what I see, it looks like your MQTT Broker in down. Double check that it's running.

**Comment by Rokscript08** [comment]
Whoops my bad. Thank you.
