### ISSUE TITLE
Network Servers / Add Error context deadline exceeded (code: 2)

### ISSUE THREAD

**Issue by denhermi** [brocaar/chirpstack-docker#37]
I've tried these server names : 

- 127.0.0.1:8000
- localhost:8000

None of them worked

**Here is the logs**
chirpstack-application-server_1  | time="2020-08-31T02:34:51Z" level=warning msg="creating insecure network-server client" server="127.0.0.1:8000"

chirpstack-application-server_1  |  time="2020-08-31T02:34:51Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {127.0.0.1:8000  <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:8000: connect: connection refused\". Reconnecting..."

chirpstack-application-server_1  | time="2020-08-31T02:34:51Z" level=error msg="finished unary call with code Unknown" ctx_id=542b4d5d-d018-4128-b5cb-ac055ef027e2 error="rpc error: code = Unknown desc = context deadline exceeded" grpc.code=Unknown grpc.method=Create grpc.service=api.NetworkServerService grpc.start_time="2020-08-31T02:34:51Z" grpc.time_ms=505.946 peer.address="127.0.0.1:52982" span.kind=server system=grpc

**Comment by bconway** [comment]
Have you checked out the end of the README? https://github.com/brocaar/chirpstack-docker#add-network-server

You will want to use `chirpstack-network-server:8000`.

**Comment by denhermi** [comment]
It works. Thank you
