### ISSUE TITLE
Containers does not init in boot 

### ISSUE THREAD

**Issue by kaciker** [brocaar/chirpstack-docker#38]
To modify the composer to be able that containers are up in case of rebooting.

**Comment by bconway** [comment]
I think that is outside the scope of an individual docker-compose file.

https://www.google.com/search?q=docker+compose+on+boot

**Comment by kaciker** [comment]
Thnaks, you right, finally with a simple command "docker update --restart unless-stopped NAME" by each container is done

**Comment by brocaar** [comment]
I'm closing this issue. This repo is intended as an example to get you started. It is expected that you need to do some customization for production purposes (e.g. making sure services are started on boot, ...).
