### ISSUE TITLE
Chirpstack network server configuration examples for US915 are incorrect (missing channels 64,65)

### ISSUE THREAD

**Issue by avillacis** [brocaar/chirpstack-docker#42]
As commented in the title:

The example in chirpstack-network-server.us915.0.toml contains the following:

`
  [network_server.network_settings]
  enabled_uplink_channels=[0, 1, 2, 3, 4, 5, 6, 7]
`

For sub-band 1, this should be instead:

`
  [network_server.network_settings]
  enabled_uplink_channels=[0, 1, 2, 3, 4, 5, 6, 7, 64]
`

The file chirpstack-network-server.us915.1.toml has a similar misconfiguration - it is missing channel 65 for a proper sub-band 2 configuration.

**Comment by brocaar** [comment]
@avillacis would you like to create a PR for this?
