### ISSUE TITLE
Defects in the file docker-compose.yml

### ISSUE THREAD

**Issue by wong-hao** [brocaar/chirpstack-docker#46]
service chirpstack-network-server has no **ports** setting.

In this case, gRPC will not be able to connect successfully even if it is the default port 8000, which is an obvious defect.

**Comment by wong-hao** [comment]
Moreover, it is necessary to change the port of the network server from 8000 to other ports, and set it in docker-compose.yml file, so that the MAC command program written by gRPC can connect to the server, which is really a big problem.

**Comment by wong-hao** [comment]
The gRPC I mentioned above is a special reference to the MAC command which uses the [API](https://www.chirpstack.io/network-server/integrate/api/).

**Comment by bconway** [comment]
This repository exists as a Docker Compose skeleton for common use cases that users can build on for their deployments. I don't think what you're asking for (external direct access to the network server) is a very common use case and appropriate for inclusion by default. You can add it to your own version, though.

**Comment by wong-hao** [comment]
> This repository exists as a Docker Compose skeleton for common use cases that users can build on for their deployments. I don't think what you're asking for (external direct access to the network server) is a very common use case and appropriate for inclusion by default. You can add it to your own version, though.

Adding such a default setting will prevent people with the above needs from wasting time searching for many solutions when they have problems, and will not have any adverse impact on people without needs.

This is profit and no harm.

Anyway, thank you for your reply, and I'm not going to stick to my ideas for your advice.

**Comment by brocaar** [comment]
> Adding such a default setting will prevent people with the above needs from wasting time searching for many solutions when they have problems, and will not have any adverse impact on people without needs.

> This is profit and no harm.

Actually, it can do harm as Docker will fail to start the container if the port is already used on the host by an other service. That is also the reason why the PostgreSQL and Redis database ports are not exposed.
