### ISSUE TITLE
Any news to support ARM?

### ISSUE THREAD

**Issue by wmmihaa** [brocaar/chirpstack-docker#48]
I've seen the "Support docker installation on RaspberryPi" #19 thread, but there has been no reply for a couple of years. Is this repo still active, and if so are there any plans of supporting ARM (or providing a tutorial)?

**Comment by brocaar** [comment]
I have started the migration from CircleCI and Docker Automated Builds to GitHub Actions. Once completed, this should make it fairly easy to add support for building ARM images for Docker.

**Comment by NRamdat** [comment]
I have build the docker containers for arm64/aarch64 if anyone needs it. So far they work like a charm, with no problems.

https://hub.docker.com/u/ineshi
