### ISSUE TITLE
chirpstack-gateway-bridge doesn't seem to be up

### ISSUE THREAD

**Issue by symeonmattes** [brocaar/chirpstack-docker#50]
Hi,

I have used the docker-compose.yml to setup my docker environment through docker-compose. Although everything seems to be up and running, the chirpstack-gateway-bridge is not up. The docker yes, but not the service inside the docker.

For simplicity I have run only bridge and mosquito, i.e. 

`docker-compose up chirpstack-gateway-bridge`

With docker ps I have:

```
CONTAINER ID   IMAGE                                         COMMAND                  CREATED          STATUS          PORTS                                       NAMES
0246623d4ae2   docker-chirpstack_chirpstack-gateway-bridge   "/usr/bin/chirpstack…"   44 minutes ago   Up 20 minutes   0.0.0.0:1700->1700/udp, :::1700->1700/udp   docker-chirpstack_chirpstack-gateway-bridge_1
a2663bda40d9   eclipse-mosquitto:2                           "/docker-entrypoint.…"   44 minutes ago   Up 21 minutes   0.0.0.0:1883->1883/tcp, :::1883->1883/tcp   docker-chirpstack_mosquitto_1
symeon@debian:/media/extra_partition/MyProjects/MbedPrograms/Prototypes/server-prototype-environment$ 
```

I login to mosquito container with nmap installed:
`docker exec -u 0 -it a2663bda40d9 /bin/sh`

```
Starting Nmap 7.80 ( https://nmap.org ) at 2021-07-11 17:25 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.0000090s latency).
Other addresses for localhost (not scanned): ::1
Not shown: 65499 closed ports
PORT     STATE SERVICE
1883/tcp open  mqtt
```

And then I login to bridge:
`docker exec -u 0 -it 0246623d4ae2 /bin/sh`

```
 nmap localhost -p 1-65535
Starting Nmap 7.91 ( https://nmap.org ) at 2021-07-11 17:26 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.0000080s latency).
Other addresses for localhost (not scanned): ::1
All 65535 scanned ports on localhost (127.0.0.1) are closed

Nmap done: 1 IP address (1 host up) scanned in 1.27 second
```
The bridge doesn't seem to be up...Is it a bug or should I do anything else?

In https://github.com/brocaar/chirpstack-docker/blob/master/configuration/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml

I have tried also to use the ip of the mosquito container which in my case was 

```
[integration.mqtt.auth.generic]
servers=["tcp://172.20.0.8:1883"]     | instead of tcp://mosquitto:1883
username=""
password=""
```

But again nothing is up

**Comment by brocaar** [comment]
Are you sure you are scanning for UDP ports?

https://nmap.org/book/scan-methods-udp-scan.html

**Comment by symeonmattes** [comment]
Hi @brocaar 

You're very right...I didn't notice it's UDP.

Thanks
Cheers
