### ISSUE TITLE
(Question) Am I able to automatically add a Network Server to the Application Server that is being deployed?

### ISSUE THREAD

**Issue by earsnot** [brocaar/chirpstack-docker#53]
As the title states, I am interested in adding the Network Server automatically to be able to get up and running without using the web interface. Hope this is the right place to ask.

**Comment by bconway** [comment]
This should probably be in the application server repo.

That being said, I think it's a good idea. It could potentially be implemented as an env/config flag that is used only on initial startup, similar to the Postgres image's `POSTGRES_PASSWORD`. Retry mechanics may be non-trivial if the requested NS is not up at the time.

**Comment by brocaar** [comment]
This is currently not supported (other than the web-interface or API integration). However, I'm currently doing some refactoring work and this add NS step will no longer be needed in the future. Stay tuned :)
