### ISSUE TITLE
support FUOTA?

### ISSUE THREAD

**Issue by magicwen666** [brocaar/chirpstack-docker#56]
When will Chirpstack-Docker support FUOTA service

**Comment by brocaar** [comment]
I'm not planning to integrate the ChirpStack FUOTA Server in the Docker example. This example is to give an easy way to get started with ChirpStack, I'm not sure if FUOTA should be included in this as it is quite a complex topic.

**Comment by magicwen666** [comment]
hi brocaars :
    I tried a few things about this, and unfortunately it didn't work.
After executing the 'docker-compose up' command, there is an error:
"chirpstack-docker-chirpstack-fuota-server-1        | time="2022-04-18T11:20:23Z" level=warning msg="storage: ping PostgreSQL database error, will retry in 2s" error="dial tcp 127.0.0.1:5432: connect: connection refused"
![Snipaste_2022-04-18_19-21-18](https://user-images.githubusercontent.com/12457033/163801206-c9e26d6a-62f6-423d-a1f2-db60f6fea5a7.jpg)
I have checked the status of docker, and the postgre(port 5432) service is running. I don't understand why this problem occurs.
Could you please share the solution to troubleshoot this problem. 
Thanks in advance!
