### ISSUE TITLE
tag : 3 ，Which version is it ？ 

### ISSUE THREAD

**Issue by zgz757183190** [brocaar/chirpstack-docker#57]
chirpstack-docker

  image: chirpstack/chirpstack-network-server:3

  3 is V3.0.0 ？？？

 NS v3.10, AS v3.15, Bridge v3.10  ？？？？

Does anyone know ？

thanks!!!

**Comment by brocaar** [comment]
https://www.chirpstack.io/project/install/docker/

Example versions:

* v.3.1.0
* v3.1.1
* v3.2.0
* v3.2.1

3 points to the latest v3.y.z version, thus v3.2.1
3.2 points to the latest v3.3.z version, thus v3.2.1
3.2.1 points obviously to v3.2.1

**Comment by zgz757183190** [comment]
Thank you very much !!!!!! brocaar-God
